FROM node:18-alpine

WORKDIR /app

# Копирование файлов проекта
COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src

# Установка зависимостей и сборка проекта
RUN npm install
RUN npm run build

# Экспозиция порта
EXPOSE 3005

# Запуск приложения в HTTP режиме
CMD ["node", "dist/server.js", "--http"] 