version: '3'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-perplexity-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ../Games:/app/Games
    restart: unless-stopped 